//[Ul/Pre] Verify M6/M8 License section in the Integration test screen displays as OK after rebooting device when user pushed M6/M8 License file to device.

// root and push m8 key and reboot
put global functions.root()
put global functions.push_dts_m6m8_key(global other.Other().dts_m6m8_key)
//disconnect device, reboot and open app
put global functions.disconnect_mobile()
put global functions.reboot()
put global functions.open_app()
//open intergration test screen.
put global main.open_integration_screen()

//check M6 M8
Try
	if global integration.check_M6M8_OK() is true then
		LogSuccess "M6/M8 License section displayed OK"
		// clean up
		cleanup
	else
		put global functions.error("M6/M8 License section did not display OK")
		// clean up
		cleanup
	end if
catch exception
	put exception 's reason
	// clean up
	cleanup
end try


to cleanup
	put global functions.close_app()
	put global functions.disconnect_mobile()
	exit to top
end cleanup










