#[Ultra] Verify user can select User setting option at Listening test
Try
	//connect device and open app
	put global functions.connect_mobile()
	put global functions.open_app()
	
	//open listening profile
	put global main.open_LP_screen()
	wait 2
	//if connect with BT route, listening profile setup dialog will appear
	//if connect with USB, then nothing happen
	put global lp.click_ok_lpsetup_bt_dialog_appear()
	wait 2
	//change value of listening profile
	changesetting
	
	//scroll down 3 times
	Repeat 3 times
		put global functions.swipeup()
	End repeat
	
	//open demo screen, select perfect hearing
	put global main.open_demo_screen()
	put global demo.select_perfect_hearing()
	
	//re-select user setting
	put global demo.select_user_setting()
	
	//check if current value is the same as user setting
	if global demo.check_current_value() is false then
		put global functions.error("Current value is not the same as User setting")
		cleanup
	else
		LogSuccess "Current value updated correctly"
	end if
	
	//cleanup
	cleanup
Catch exception
	put exception 's error
	cleanup
End try

to cleanup
	// reset listening profile
	put global demo.reset_listening_profile()
	
	//close app and disconnect
	put global functions.close_app()
	put global functions.disconnect_mobile()
	exit to top
end cleanup

to changesetting
	Repeat 4 times
		wait 2
		put global lp.change_value()
		wait 2
		put global lp.click_next()
	End repeat
	wait 3
	put global lp.click_ok_success_dialog_appear()
end changesetting
