//[Ul/Pre] Verify DE,Treble,Bass slider value on IT screen is reflected to PersonalPre screen.


//connect device and open app
put global functions.connect_mobile()
put global functions.open_app()
// go to integration test screen
put global main.open_integration_screen()

///swipe up
Repeat 4 times
	put global functions.swipeup()
	wait 2
End Repeat

// Slide Dialog Enhancement / Bass / Treble boost
put global personalpref.change_treble(600)
put global personalpref.change_DE(600)
put global personalpref.change_bass(600)

// Capture screen
put global integration.capture_Audio_levels(current_value_of_boostsliders) into current_value_of_boostsliders

//Go back to Main Screen and go to Personal Audio Preference
PressBackButton
put global main.open_personalpref_screen()

//Swipe up
Repeat 2 times
	put global functions.swipeup()
	wait 2
End repeat

//Check if the value of Boost slides at Pesonal Audio Preference Screen indicate with the value of Boost sliders at Integration Test Screen
if global functions.check_imagefound_image(current_value_of_boostsliders) is true then
	LogSuccess "Boost slider value on Integration Test screen is reflect to Personal Audio Preference screen"
	//clean up
	cleanup
else
	put global functions.error("Boost slider value on Integration Test screen is NOT reflect to Personal Audio Preference screen")
	cleanup
	return false
end if


to cleanup
	put global personalpref.reset_setting()
	put global functions.close_app()
	put global functions.disconnect_mobile()
	exit to top
end cleanup




