//[Ul/Pre] Verify the Broadcast API ON/Off status is preserved after reboot

//connect mobile and open app
put global functions.connect_mobile()
put global functions.open_app()
//open Integration Test screen
put global main.open_integration_screen()
// turn off API toggle
put global integration.turn_off_API()
wait 5
put global functions.captureimage(API_OFF) into API_OFF

//reboot device and open app and go to Integration test screen
put global functions.reboot()
put global functions.open_app()
put global main.open_integration_screen()
wait 5
if global functions.check_imagefound_image(API_OFF) is true then 
	put global integration.turn_on_API()
	wait 5
	put global functions.captureimage(API_ON) into API_ON
	
	//reboot device and open app and go to Integration Test screen
	put global functions.reboot()
	put global functions.open_app()
	put global main.open_integration_screen()
	wait 5
	if global functions.check_imagefound_image(API_ON) is true then
		LogSuccess "The Broadcast API ON/Off status is preserved after reboot device"
		//cleap up
		cleanup
	else
		put global functions.error("The Broadcast API ON/Off status is NOT preserved after reboot device")
		//clean up
		cleanup
	end if
else
	put global functions.error("The Broadcast API ON/Off status is NOT preserved after reboot device")
	//clean up
	cleanup
end if

to cleanup
	put global functions.close_app()
	put global functions.disconnect_mobile()
	exit to top
end cleanup


